# Generated by Django 5.1.2 on 2025-01-23 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DadosHidricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_med_jan', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_fev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_mar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_abr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_mai', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_jun', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_jul', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_ago', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_set', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_out', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_nov', models.DecimalField(decimal_places=4, max_digits=10)),
                ('t_med_dez', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_jan', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_fev', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_mar', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_abr', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_mai', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_jun', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_jul', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_ago', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_set', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_out', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_nov', models.DecimalField(decimal_places=4, max_digits=10)),
                ('precip_md_dez', models.DecimalField(decimal_places=4, max_digits=10)),
                ('estacao', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade')),
            ],
        ),
        migrations.AddField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.estado'),
        ),
    ]
