# Generated by Django 5.1.2 on 2025-01-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dadoshidricos',
            name='precipitacao',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.RenameField(
            model_name='dadoshidricos',
            old_name='pa_max_hora_mb',
            new_name='temperatura',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='pa_min_hora_mb',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='pa_nivel_estacao_mb',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='radiacao_global_kjm2',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_ar_bulbo_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_max_hora_antes_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_min_hora_antes_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_orvalho_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_orvalho_max_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='temp_orvalho_min_c',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='umid_rel_max_hora_per',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='umid_rel_min_hora_per',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='umid_rel_per',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='vento_direcao_gr',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='vento_rajada_ms',
        ),
        migrations.RemoveField(
            model_name='dadoshidricos',
            name='vento_velocidade_ms',
        ),
        migrations.AddField(
            model_name='dadoshidricos',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.cidade'),
        ),
        migrations.DeleteModel(
            name='Precipitacao',
        ),
    ]
