# Generated by Django 5.1.2 on 2025-02-28 17:43

from django.db import migrations

# Referência:
# https://docs.djangoproject.com/en/5.1/topics/migrations/#data-migrations

def load_ufs(apps, schema_editor):
    Estado = apps.get_model("app", "Estado")
    uf = Estado()
    uf.nome = "Rio Grande do Norte"
    uf.save()

# Criar método similar ao load_ufs() para carregar Cidades e DadosHídricos

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_ufs), # Repetir essa linha para chamar os métodos das Cidades e DadosHídricos
    ]
