# Generated by Django 5.1.2 on 2025-01-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_dadoshidricos_precipitacao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cidade',
            old_name='nome',
            new_name='estacao',
        ),
    ]
